"use strict";
const hre=require("hardhat"),fs=require("fs");
const {ethers}=hre;
const MORPHO="0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb",AAVE_POOL="0xA238Dd80C259a72e81d7e4664a9801593F98d1c5",WAD=10n**18n,SCALE=10n**36n;
const divUp=(a,b)=>(a+b-1n)/b,toAssetsUp=(shares,assets,totalShares)=>totalShares===0n?0n:divUp(shares*assets,totalShares);
function bound(p,m,price,lltv){const debt=toAssetsUp(BigInt(p.borrowShares),BigInt(m.totalBorrowAssets),BigInt(m.totalBorrowShares));const collateral=BigInt(p.collateral);if(!debt||!collateral)throw new Error("EMPTY_POSITION");const maxRepay=debt;const maxSeize=collateral;return {repaidAssets:maxRepay,seizedAssets:maxSeize};}
async function main(){
 const candidate=JSON.parse(process.env.ARBIFLOW_MAINNET_SAFETY_CANDIDATE_JSON||"null");if(!candidate?.marketId||!candidate?.user)throw new Error("CANDIDATE_REQUIRED");if(!process.env.BASE_RPC_URL)throw new Error("BASE_RPC_URL_REQUIRED");
 await hre.network.provider.request({method:"hardhat_reset",params:[{forking:{jsonRpcUrl:process.env.BASE_RPC_URL}}]});const [tester]=await ethers.getSigners();const sourceBlock=await ethers.provider.getBlockNumber();await hre.network.provider.send("evm_mine");
 const morpho=new ethers.Contract(MORPHO,["function idToMarketParams(bytes32) view returns(address loanToken,address collateralToken,address oracle,address irm,uint256 lltv)","function accrueInterest((address,address,address,address,uint256))","function market(bytes32) view returns(uint128 totalSupplyAssets,uint128 totalSupplyShares,uint128 totalBorrowAssets,uint128 totalBorrowShares,uint128 lastUpdate,uint128 fee)","function position(bytes32,address) view returns(uint256 supplyShares,uint128 borrowShares,uint128 collateral)"],tester);
 const mp=await morpho.idToMarketParams(candidate.marketId);if(mp.loanToken===ethers.ZeroAddress)throw new Error("UNKNOWN_MARKET");await (await morpho.accrueInterest([mp.loanToken,mp.collateralToken,mp.oracle,mp.irm,mp.lltv])).wait();const m=await morpho.market(candidate.marketId),p=await morpho.position(candidate.marketId,candidate.user),oracle=new ethers.Contract(mp.oracle,["function price() view returns(uint256)"],tester),price=await oracle.price(),debt=toAssetsUp(BigInt(p.borrowShares),BigInt(m.totalBorrowAssets),BigInt(m.totalBorrowShares));if(!debt||!BigInt(p.collateral))throw new Error("EMPTY_POSITION");const hf=BigInt(p.collateral)*price/SCALE*BigInt(mp.lltv)/debt;
 const base={success:true,version:"4.39.0",sourceForkBlockNumber:sourceBlock,marketId:candidate.marketId,borrower:candidate.user,exactAccruedHealthFactorWad:hf.toString(),exactAccruedLiquidatable:hf<WAD,stateClassification:"FRESH_BASE_FORK_EXACT_ACCRUAL_NO_ORACLE_MUTATION",controlledOracleShockUsed:false,mainnetDeployment:false,mainnetBroadcast:false,mainnetStateChanged:false,fundsMovedOnMainnet:false,generatedAt:new Date().toISOString()};
 if(hf>=WAD){const report={...base,classification:"MAINNET_EXECUTION_SAFETY_GATE_WAIT",readyForExplicitExecutionApproval:false,reason:"CANDIDATE_NOT_LIQUIDATABLE_AFTER_EXACT_FORK_ACCRUAL"};fs.writeFileSync(process.env.ARBIFLOW_MAINNET_SAFETY_REPORT||"mainnet-safety-gate-report-4390.json",JSON.stringify(report,null,2));console.log(JSON.stringify(report));return;}
 const exAddr=(process.env.ARBIFLOW_PRODUCTION_EXECUTOR_ADDRESS||"").trim(),owner=(process.env.ARBIFLOW_PRODUCTION_OWNER_ADDRESS||"").trim();if(!/^0x[a-fA-F0-9]{40}$/.test(exAddr)||!/^0x[a-fA-F0-9]{40}$/.test(owner))throw new Error("PRODUCTION_EXECUTOR_OR_OWNER_NOT_CONFIGURED");const code=await ethers.provider.getCode(exAddr);if(!code||code==="0x")throw new Error("PRODUCTION_EXECUTOR_CODE_MISSING_ON_FORK");const readEx=new ethers.Contract(exAddr,["function OWNER() view returns(address)","function AAVE_POOL() view returns(address)","function MORPHO() view returns(address)"],ethers.provider);const [bo,ba,bm]=await Promise.all([readEx.OWNER(),readEx.AAVE_POOL(),readEx.MORPHO()]);if(bo.toLowerCase()!==owner.toLowerCase()||ba.toLowerCase()!==AAVE_POOL.toLowerCase()||bm.toLowerCase()!==MORPHO.toLowerCase())throw new Error("PRODUCTION_EXECUTOR_BINDING_MISMATCH_ON_FORK");
 await hre.network.provider.send("hardhat_impersonateAccount",[owner]);await hre.network.provider.send("hardhat_setBalance",[owner,"0x56BC75E2D63100000"]);const ownerSigner=await ethers.getSigner(owner),artifact=await hre.artifacts.readArtifact("ArbiFlowAtomicExecutor430"),ex=new ethers.Contract(exAddr,artifact.abi,ownerSigner),b=bound(p,m,price,BigInt(mp.lltv)),premium=divUp(b.repaidAssets*5n,10000n),minNet=Number(process.env.ARBIFLOW_PRODUCTION_MIN_NET_PROFIT_USD||15);if(!Number.isFinite(minNet)||minNet<15)throw new Error("INVALID_MINIMUM_NET_PROFIT_USD");
 const request=async(url,options={})=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{...options,headers:{"X-Client-Id":((process.env.ARBIFLOW_KYBER_CLIENT_ID||"ArbiFlow").trim()||"ArbiFlow"),Accept:"application/json",...(options.headers||{})},signal:c.signal}),body=await r.text();let data=null;try{data=JSON.parse(body)}catch{}return {ok:r.ok,status:r.status,body,data}}finally{clearTimeout(t)}};
 const route=await request("https://aggregator-api.kyberswap.com/base/api/v1/routes?"+new URLSearchParams({tokenIn:mp.collateralToken,tokenOut:mp.loanToken,amountIn:b.seizedAssets.toString(),excludeRFQSources:"true",onlyScalableSources:"true",gasInclude:"true"})),summary=route.data?.data?.routeSummary||null,router=route.data?.data?.routerAddress||null;if(!route.ok||!summary?.amountOut||!router)throw new Error(`KYBER_ROUTE_FAILED:${route.status}`);
 const build=await request("https://aggregator-api.kyberswap.com/base/api/v1/route/build",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({routeSummary:summary,sender:exAddr,recipient:exAddr,slippageTolerance:Number(process.env.ARBIFLOW_KYBER_SLIPPAGE_BPS||50),enableGasEstimation:false,source:"ArbiFlow"})}),kd=build.data?.data||null,swapData=kd?.data||null,swapTarget=kd?.routerAddress||null;if(!build.ok||!swapData||!/^0x[0-9a-fA-F]+$/.test(swapData)||!/^0x[a-fA-F0-9]{40}$/.test(swapTarget||"")||swapTarget.toLowerCase()!==router.toLowerCase())throw new Error("KYBER_BUILD_FAILED_OR_ROUTER_MISMATCH");
 const token=new ethers.Contract(mp.loanToken,["function decimals() view returns(uint8)"],tester),dec=Number(await token.decimals()),amountOutUsd=Number(summary.amountOutUsd),loanOutHuman=Number(ethers.formatUnits(summary.amountOut,dec)),loanUsd=amountOutUsd/loanOutHuman;if(!Number.isFinite(loanUsd)||loanUsd<=0)throw new Error("LOAN_TOKEN_USD_UNAVAILABLE");const feeData=await ethers.provider.getFeeData(),gasPrice=feeData.gasPrice??feeData.maxFeePerGas;if(!gasPrice)throw new Error("GAS_PRICE_UNAVAILABLE");let ethUsd=null;if(mp.loanToken.toLowerCase()==="0x4200000000000000000000000000000000000006")ethUsd=loanUsd;else{const gu=Number(summary.gasUsd),gg=Number(summary.gas);if(Number.isFinite(gu)&&gu>0&&Number.isFinite(gg)&&gg>0){const ge=Number(ethers.formatEther(BigInt(Math.ceil(gg))*gasPrice));if(ge>0)ethUsd=gu/ge;}}if(!Number.isFinite(ethUsd)||ethUsd<=0)throw new Error("ETH_USD_PRICE_UNAVAILABLE");
 // First build a conservative $15+gas profit floor using configured max gas, then estimate the exact candidate transaction.
 const maxGas=BigInt(process.env.ARBIFLOW_PRODUCTION_MAX_ATOMIC_GAS||"900000"),reserveUsd=Number(ethers.formatEther(maxGas*gasPrice))*ethUsd,initialMinProfitRaw=BigInt(Math.ceil(((minNet+reserveUsd)/loanUsd)*(10**dec))),initialRequiredOut=b.repaidAssets+premium+initialMinProfitRaw;if(BigInt(summary.amountOut)<initialRequiredOut)throw new Error("KYBER_ROUTE_OUTPUT_BELOW_INITIAL_NET_PROFIT_REQUIREMENT");
 let plan={market:{loanToken:mp.loanToken,collateralToken:mp.collateralToken,oracle:mp.oracle,irm:mp.irm,lltv:mp.lltv},borrower:candidate.user,flashAmount:b.repaidAssets,seizedAssets:b.seizedAssets,minLoanAssetOut:initialRequiredOut,allowanceSpender:router,swapTarget,swapCalldata:swapData,profitRecipient:owner,minProfitRaw:initialMinProfitRaw};const gasEstimate=await ex.executeForkPlan.estimateGas(plan);const gasBudget=gasEstimate*110n/100n;if(gasBudget>maxGas)throw new Error(`TRANSACTION_GAS_BUDGET_EXCEEDS_CONFIGURED_MAX:${gasBudget}:${maxGas}`);const gasUsd=Number(ethers.formatEther(gasBudget*gasPrice))*ethUsd,requiredGrossUsd=minNet+gasUsd,minProfitRaw=BigInt(Math.ceil((requiredGrossUsd/loanUsd)*(10**dec))),requiredOut=b.repaidAssets+premium+minProfitRaw;if(BigInt(summary.amountOut)<requiredOut)throw new Error("KYBER_ROUTE_OUTPUT_BELOW_FINAL_NET_PROFIT_REQUIREMENT");plan={...plan,minLoanAssetOut:requiredOut,minProfitRaw};const finalGasEstimate=await ex.executeForkPlan.estimateGas(plan),finalGasBudget=finalGasEstimate*110n/100n;if(finalGasBudget>maxGas)throw new Error(`FINAL_TRANSACTION_GAS_BUDGET_EXCEEDS_CONFIGURED_MAX:${finalGasBudget}:${maxGas}`);
 const report={...base,classification:"MAINNET_EXECUTION_SAFETY_GATE_PASSED",readyForExplicitExecutionApproval:true,productionExecutorAddress:exAddr,productionOwner:owner,productionBindingsVerifiedOnFork:true,kyberRouteValidated:true,kyberBuildValidated:true,kyberCalldataExecuted:false,exactRepaidAssetsRaw:b.repaidAssets.toString(),seizedAssetsRaw:b.seizedAssets.toString(),routeQuotedOutputRaw:summary.amountOut,builtOutputRaw:kd.amountOut??null,expectedAavePremiumRaw:premium.toString(),transactionSpecificGasEstimate:finalGasEstimate.toString(),gasBudgetWith10PctReserve:finalGasBudget.toString(),configuredMaxAtomicGas:maxGas.toString(),minimumNetProfitUsd:minNet,modeledGasUsd:Number(ethers.formatEther(finalGasBudget*gasPrice))*ethUsd,requiredGrossProfitUsd:minNet+Number(ethers.formatEther(finalGasBudget*gasPrice))*ethUsd,minProfitRaw:minProfitRaw.toString(),requiredAtomicOutputRaw:requiredOut.toString(),loanTokenUsd:loanUsd,liveExecutionEnabled:false,nextGate:"SEPARATE_EXPLICIT_USER_APPROVAL_REQUIRED_BEFORE_ANY_MAINNET_TRANSACTION"};fs.writeFileSync(process.env.ARBIFLOW_MAINNET_SAFETY_REPORT||"mainnet-safety-gate-report-4390.json",JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}
main().catch(e=>{console.error(e);process.exitCode=1});
