'use strict';
const assert=require('node:assert/strict');const {chains,cexs,inventory,mount}=require('./registry');
assert.equal(chains.length,25);assert.equal(cexs.length,25);
assert.equal(chains.filter(c=>c.original).length,15);assert.equal(cexs.filter(c=>c.original).length,15);
assert.equal(new Set(chains.map(c=>c.id)).size,25);assert.equal(new Set(cexs.map(c=>c.id)).size,25);
assert.equal(new Set(chains.filter(c=>c.chainId!==null).map(c=>c.chainId)).size,23);
assert.ok(chains.every(c=>!c.enabled&&!c.verified));assert.ok(cexs.every(c=>!c.enabled&&!c.verified));
assert.equal(inventory().mainnetBroadcast,false);
const routes={};mount({get:(p,h)=>{routes[p]=h}});assert.ok(routes['/api/expansion/status']);assert.ok(routes['/api/expansion/inventory']);
console.log('PASS: 25 chains, 25 CEXs, original 15 preserved in each, unique identifiers, disabled by default, read-only endpoints registered');
