"use strict";
const assert=require('node:assert/strict');
const registry=require('./registry');
const fs=require('node:fs');
const {probeEvmChain,rpcEnvironmentNames}=require('./manual-rpc-probe');
assert.equal(registry.chains.length,25);
const serverSource=fs.readFileSync(require('node:path').join(__dirname,'server.js'),'utf8');
for(const route of ['/api/expansion-25x25/phase3-probe','/api/expansion-25x25/phase4-config','/api/expansion-25x25/phase4-probe']) assert.ok(serverSource.includes(route),route);
for(const key of ['gnosis','metis','sonic','celo','unichain']) assert.ok(registry.chains.some(c=>c.key===key && Number.isInteger(c.chainId)),key);
assert.equal(registry.exchanges.length,25);
assert.equal(new Set(registry.chains.map(x=>x.key)).size,25);
assert.equal(new Set(registry.exchanges.map(x=>x.key)).size,25);
assert.equal(rpcEnvironmentNames('base')[0],'BASE_RPC_URL');
assert.equal(rpcEnvironmentNames('bnb')[0],'BNB_RPC_URL');
(async()=>{
  const blocked=await probeEvmChain({url:'http://127.0.0.1:3000',expectedChainId:1});
  assert.equal(blocked.reachable,false);
  assert.equal(blocked.status,'INVALID_RPC_URL');
  assert.equal(registry.safety.mainnetBroadcast,false);
  console.log('PASS: 25 chains, 25 exchanges, Phase 3 retained, Phase 4 endpoints, manual RPC safety');
})().catch(e=>{console.error(e);process.exitCode=1});
